name: CI
on: 
  workflow_dispatch:

defaults:
  run:
    working-directory: example

jobs:
  build_windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
